config/routes.rb
JobBoard::Application.routes.draw do
  
  root to: "jobs#premium"
  
  resources :jobs do
  	post "comments", to: "comments#create"
  end
	
	delete "comments/:id", to: "comments#destroy", as: :comment
	
  get "hello/world"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :job_id, :name
  validates_presence_of :body, :name
  
  belongs_to :job  
end

app/models/job.rb
# encoding: utf-8
class Job < ActiveRecord::Base
  attr_accessible :description, :title, :premium
  
#  validates_presence_of :title, :description #validação para mais de uma propriedade
  validates :title, :presence => {:message => "O título é obrigatório."} 	#com sintax sugar ficaria validates :title, :presence => true
  validates("description", {:presence => true}) #com sintax sugar ficaria validates :description, :presence => true
  
  scope :most_recent, order("created_at DESC")
  
  has_many :comments  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@job = Job.find(params[:job_id])
		@comment = @job.comments.build(params[:comment])
		if @job.save
			flash[:notice] = 'Comment was created with success!'
		else
			flash[:alert] = "Comment can't created!"
		end	
		redirect_to @job
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to @comment.job, notice: "Comment destroyed with success!"
	end
	
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def world
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.most_recent.paginate(page: params[:page], per_page: 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end
	
	def premium
		@jobs = Job.where(premium:true).most_recent.paginate(page: params[:page], per_page: 5)
	end
	
  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

	def job_title(job)
		title = h(job.title)
		
		if (job.premium)
			title + content_tag(:strong, " (premium)")
		else
			title
		end		
	end
end

app/views/comments/_comment.html.erb
<h4><%= comment.name %> said:</h4>
<%= simple_format comment.body %>
Sent <%= time_ago_in_words comment.created_at %> ago
<%= link_to 'Destroy', comment_path(comment), method: :delete, 
confirm: 'Are you sure?' %>

app/views/comments/_form.html.erb
<%= form_for [@job, Comment.new] do |f| %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>	
	<div class="field">
		<%= f.label :body %>
		<%= f.text_area :body %>
	</div>
	
	<div class="actions">
		<%= f.submit 'Send' %>
	</div>
<% end %>				

app/views/hello/world.html.erb
<h1>Hello World</h1>
<strong><%= Time.now %></strong>

app/views/jobs/_form.html.erb
<%= form_for @job, :html => {:class => "form-horizontal"} do |f| %>
  
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :premium, :class => "control-label" %>
    <div class="controls">
      <%= f.check_box :premium, :class => "checkbox" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => "control-label" %>
    <div class="controls">
      <%= f.text_area :description, :rows => 3 %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit  :class => "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<h3>
	<%= job.title %>
	<% if job.premium %>
		<strong>(premium)</strong>
	<% end %>
</h3>

<%= simple_format job.description %>

<p>
	<%= pluralize(job.comments.size, 'Comment') %>
    <%= link_to 'Show', job %> |
    <%= link_to 'Edit', edit_job_path(job) %> |
    <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>			

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<%= render @jobs %>
<%= will_paginate @jobs %>

<br />

<%= link_to 'New Job', new_job_path %>
<br/>
<%= link_to 'Hello World', hello_world_path %>
<%= link_to 'Premium jobs', root_path %>	

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/premium.html.erb
<h1>Premium jobs</h1>

<%= render @jobs %>
<%= will_paginate @jobs %>

<br />

<%= link_to 'New Job', new_job_path %>
<br/>
<%= link_to 'Hello World', hello_world_path %>
<%= link_to 'All jobs', jobs_path %>	

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>
  <%= job_title @job %>
</h1>

<%= simple_format @job.description %>

<p>
	<%= pluralize @job.comments.size, 'Comment' %> |
	<%= link_to 'Edit', edit_job_path(@job) %> |
	<%= link_to 'Back', jobs_path %>
</p>

<h2>Send a new Comment</h2>
<%= render 'comments/form' %>

<h2>Comments</h2>
<%= render @job.comments %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobBoard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">    
    <%= link_to 'Job Board', root_path, { :class => 'brand' } %>
    <ul class="nav">
      <li class="active">
        <%= link_to root_path do %>
          <i class="icon-star-empty"></i> Premium
        <% end %>  
      </li>
      <li>
        <%= link_to jobs_path do %>
          <i class="icon-star"></i> All jobs
        <% end %>
      </li>
      <li>
        <%= link_to new_job_path do %>
          <i class="icon-file"></i> New job
        <% end %>
      </li>         
      <li>
        <%= link_to hello_world_path do %>
          <i class="icon-flag"></i> Hello World
        <% end %>
      </li>         
    </ul>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>